// ===========================================================================
// Generated by PerfFake.tt
// ===========================================================================

using System;

namespace OneOf.Tests
{
    public abstract class PerfFakeBase
    {
        public FakeType Type { get; }
        protected PerfFakeBase(FakeType type = FakeType.Base)
        {
            Type = type;
        }
        public int BaseProp { get; } = 0;
    }
    public enum FakeType
    {
        Base = 0,
        One = 1,
        Two = 2,
        Three = 3,
        Four = 4,
        Five = 5,
        Six = 6
    }
    public class One : PerfFakeBase
    {
        public One() : base(FakeType.One){}
        public int OneProp { get; } = 1;
    }
    public class Two : PerfFakeBase
    {
        public Two() : base(FakeType.Two){}
        public int TwoProp { get; } = 2;
    }
    public class Three : PerfFakeBase
    {
        public Three() : base(FakeType.Three){}
        public int ThreeProp { get; } = 3;
    }
    public class Four : PerfFakeBase
    {
        public Four() : base(FakeType.Four){}
        public int FourProp { get; } = 4;
    }
    public class Five : PerfFakeBase
    {
        public Five() : base(FakeType.Five){}
        public int FiveProp { get; } = 5;
    }
    public class Six : PerfFakeBase
    {
        public Six() : base(FakeType.Six){}
        public int SixProp { get; } = 6;
    }
    public static class PerfOneOfs
    {
        public static OneOf<PerfFakeBase,One,Two,Three,Four> One = new One();
        public static OneOf<PerfFakeBase,One,Two,Three,Four> Two = new Two();
        public static OneOf<PerfFakeBase,One,Two,Three,Four> Three = new Three();
        public static OneOf<PerfFakeBase,One,Two,Three,Four> Four = new Four();
        public static OneOf<PerfFakeBase,One,Two,Three,Four> Five = new Five();
        public static OneOf<PerfFakeBase,One,Two,Three,Four> Six = new Six();
    }
}
